### ISSUE TITLE
The function 'is_stable'

### ISSUE THREAD

**Issue by dongqunxi** [scot-dev/scot#177] opened 2016-08-17 06:40 UTC
Hi @mbillingr, 

I am using the scot tool-kit to analyse multi-trials MEG data. Can you give me a simple introduction of the process of the 'is_stable' function. Since I checked the book you took as the reference, that is hard to find a good explanation of the stable test. Thanks a lot!

**Comment by cbrnr** [comment] 2016-08-17 06:55
The procedure implemented in `is_stable` is described in the book on pages 15-16. Basically, a VAR(1) model is stable if all eigenvalues of the parameter matrix have modulus less than 1 (this is equation 2.1.7). Now the same thing is true for a VAR(p) model, because it can be written like a VAR(1). The function `is_stable` is apparently implementing the block matrices defined at the bottom of page 15 and then performs the check according to 2.1.9. Alternatively, I guess you could also implement this test according to 2.1.12.

**Comment by dongqunxi** [comment] 2016-08-17 07:24
Thanks @cbrnr ! I checked the detail of the codes of 'is_stable',
```ruby 
top_block = []
        for i in range(p):
            top_block.append(self.coef[:, i::p])
top_block = np.hstack(top_block)
```
it is different from stable test of matlab function, in Matlab it is similar as
```
for i in range(m)
     top_block.append(self.coef[:, i*p:(i+1)*p])
```
That also leads different results of the stable test. Can you explain why do you arrange top_block as this way?

**Comment by mbillingr** [comment] 2016-11-09 20:16
Sorry for the delay. I no longer have access to the book to check the implementation. Do you still have it @cbrnr? 

Regarding the test, the fact that the model is initialized as a VAR(1) model is completely irrelevant. The assignment to `var.coef` overrules the model order setting. What we have instead is a univariate AR(2) model. This also explains the rule of thumb: if all coefficients in a UAR model have the same sign the signals will blow up if sum(coef) > 1, oscillate if sum(coef)==1, and remain bounded if sum(coef) < 1.

It occurs to me that we test stability only on UAR models. Maybe something that should be addressed...

**Comment by cbrnr** [comment] 2016-11-10 09:00
@mbillingr yes, I still have the book. I'll send you the relevant pages via email.

If `var.coef` overrides the model order setting, everything is clear. However, it would not be good if the stability check only worked for UAR models. Let's discuss further after you've read the relevant pages in the book.

**Comment by mbillingr** [comment] 2016-11-11 17:42
Thank you. I will try to find some time this weekend :)

**Comment by mbillingr** [comment] 2016-11-11 19:59
Function `is_stable` seems correct to me. Please verify my reasoning:

The book states on page 15:
> ... we call a VAR(1) process *stable* if all Eigenvalues of A have modulus less than 1.

The function first represents the VAR(p) coefficients in VAR(1) form, and then checks if all Eigenvalues are <1.

The VAR(1) representation is on the bottom of page 15. To construct it, we need to obtain the sub-matrices A_1, A_2 ... A_p.

Our coefficients are arranged as such:

    shape [m, m*p], with sub matrices arranged as follows:
    +------+------+------+------+
    | b_00 | b_01 | ...  | b_0m |
    +------+------+------+------+
    | b_10 | b_11 | ...  | b_1m |
    +------+------+------+------+
    | ...  | ...  | ...  | ...  |
    +------+------+------+------+
    | b_m0 | b_m1 | ...  | b_mm |
    +------+------+------+------+
    Each sub matrix b_ij is a column vector of length p that contains the
    filter coefficients from channel j (source) to channel i (sink).

Therefore, submatrix A_k is formed by taking every p-th column, starting at index k.

(Note: the block diagonal matrix can probably be more efficiently constructed with `sp.linalg.block_diag(*([im] * (p - 1)))`) instead of the for-loop.


We shall definitely add a few tests that use more complex models. (Although even a univariate AR(p>1) model is converted to a VAR(1) model, so in principle our current test should be sufficient.)

**Comment by cbrnr** [comment] 2016-11-17 09:07
Thanks @mbillingr, I can confirm that the function works as intended. I'm closing this issue, but there are two things I don't like about the current implementation:

1. The user sets the model order `p` when creating a `VARBase` object. This instance variable seems irrelevant, since `p` is inferred from the shape of the `coef` instance variable. We should do something about it.
2. I still think the coefficients should go into a 3D array - the current arrangement is not intuitive and cannot be inferred without reading the docstring time and again.

What's your take on these two points?

**Closed by cbrnr** 2016-11-17 09:07 UTC

**Comment by mbillingr** [comment] 2016-11-19 19:54
Since you asked I'll answer here, although the issue is closed. :)

1. The instance variable is needed for fitting the model. I'm not sure what to do about that, though... maybe make `coef` an attribute that updates `p` when set?

2. 3D array seems like a good idea to me. If I'm not mistaken it would only be a matter of reshaping, so we don't even have to change the algorithms.

**Comment by cbrnr** [comment] 2016-11-19 20:05
Regarding 1, why do we need `p` in the first place if it can always be derived from the shape of `coef`? Seems redundant to me, and it's confusing if these two variables get out of sync.

Regarding 2, I think so too. Which shape do you propose? I'd put the lag into dimension 0 or 2 - what do you think?

**Comment by mbillingr** [comment] 2016-12-06 19:37
We need `p` so that `fit` knows what model order we want.

Lag in dimension 0 or 2 is both fine. I think 2 is slightly more preferable because 1) in our data time is also in the last dimension and 2) our old format can be easily reshaped to this.

**Comment by cbrnr** [comment] 2016-12-06 20:16
OK, right, but we should do something to avoid having `p` and the shape of `coef` out of sync.

Then let's reshape!

Would you mind creating 2 new issues so that we don't have to continue our discussion in this closed and totally unrelated issue :-)? Or you can always create PRs instead :-P!
